//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportSchedular.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DSM_tb
    {
        public int ID { get; set; }
        public double dsm_charges { get; set; }
    }
}
