//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportSchedular.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LoginDatabaseEntities : DbContext
    {
        public LoginDatabaseEntities()
            : base("name=LoginDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<RepMaster> RepMasters { get; set; }
        public virtual DbSet<ReportList> ReportLists { get; set; }
        public virtual DbSet<DSM_tb> DSM_tb { get; set; }
        public virtual DbSet<ABT_tb> ABT_tb { get; set; }
        public virtual DbSet<Schedular> Schedulars { get; set; }
    }
}
